enum BoardTitles {
  ENTITIES = 'ENTITIES - DAVID',
  NAMESTEAMSPACE = 'NAMES TEAM SPACE',
  ASSETS = 'ASSETS',
  RELATIONSHIPS = 'RELATIONSHIPS',
  BTR = 'BUSINESS TRANSPARENCY REGISTER',
  ENTITIESOLGA = 'ENTITIES - OLGA',
}

export default BoardTitles
