enum BoardTitles {
    ENTITIES = 'ENTITIES',
    NAMESTEAMSPACE = 'NAMES TEAM SPACE',
    ASSETS = 'ASSETS',
    RELATIONSHIPS = 'RELATIONSHIPS',
    BTR = 'BENEFICIAL OWNERSHIP'
}

export default BoardTitles
