enum BoardTitles {
  ENTITIES = 'ENTITIES',
  NAMESTEAMSPACE = 'NAMES TEAM SPACE',
  ASSETS = 'ASSETS',
  RELATIONSHIPS = 'RELATIONSHIPS',
  BTR = 'BUSINESS TRANSPARENCY REGISTER'
}

export default BoardTitles
